// ================================================
// SAYWEE - Language System
// language.js
// ================================================

const TRANSLATIONS = {
  ko: {
    // Header
    nav_home: '홈',
    nav_shop: '쇼핑',
    nav_countries: '국가별',
    nav_event: '이벤트',
    nav_blog: '블로그',
    nav_reviews: '리뷰',
    nav_about: '소개',
    nav_contact: '문의',
    search_placeholder: '상품을 검색하세요...',
    // Hero
    hero1_tag: '새로운 입고',
    hero1_title: '아시아의 맛을\n한 곳에서',
    hero1_desc: '7개국 최고의 식품과 식재료를 직접 만나보세요.',
    hero1_btn: '지금 쇼핑하기',
    hero2_tag: '베스트셀러',
    hero2_title: '한국 라면의\n정석',
    hero2_desc: '신라면, 삼양 불닭볶음면 등 인기 한국 라면을 만나보세요.',
    hero2_btn: '라면 보기',
    hero3_tag: '특별 할인',
    hero3_title: '버블티를\n집에서',
    hero3_desc: '대만 정통 버블티 키트로 카페 맛을 집에서 즐기세요.',
    hero3_btn: '지금 주문',
    // Sections
    section_country: '국가별 쇼핑',
    section_country_sub: '원하는 나라의 맛을 선택하세요',
    section_bestseller: '베스트셀러',
    section_bestseller_sub: '가장 많이 팔리는 인기 상품',
    section_new: '신상품',
    section_new_sub: '새롭게 입고된 상품들',
    section_drinks: '아시아 음료',
    section_drinks_sub: '각국의 인기 음료 컬렉션',
    section_snacks: '아시아 스낵',
    section_snacks_sub: '맛있는 아시아 간식 모음',
    section_reviews: '고객 리뷰',
    section_reviews_sub: '실제 구매 고객의 솔직한 후기',
    section_story: '세이위 이야기',
    section_insta: '인스타그램 팔로우하기',
    view_all: '전체 보기',
    // Product Card
    add_to_cart: '장바구니 추가',
    add_to_wishlist: '위시리스트',
    quick_view: '빠른 보기',
    reviews_count: '개 리뷰',
    sold_count: '판매됨',
    // Countries
    country_korea: '한국',
    country_japan: '일본',
    country_china: '중국',
    country_vietnam: '베트남',
    country_thailand: '태국',
    country_india: '인도',
    country_taiwan: '대만',
    // Cart
    cart_title: '장바구니',
    cart_empty: '장바구니가 비어 있습니다',
    cart_empty_sub: '쇼핑을 시작하고 좋아하는 상품을 담아보세요',
    go_shopping: '쇼핑하러 가기',
    subtotal: '소계',
    shipping: '배송비',
    free_shipping: '무료',
    total: '합계',
    checkout: '결제하기',
    coupon_placeholder: '쿠폰 코드 입력',
    apply: '적용',
    remove: '삭제',
    // Product Detail
    tab_description: '상품 설명',
    tab_nutrition: '영양 정보',
    tab_reviews: '리뷰',
    tab_qa: 'Q&A',
    add_cart: '장바구니에 담기',
    buy_now: '바로 구매',
    add_wish: '위시리스트에 추가',
    delivery_title: '배송 정보',
    shipping_fee: '배송비',
    delivery_time: '배송 기간',
    return_policy: '반품 정책',
    refund_policy: '환불 정책',
    shipping_fee_val: '₩3,000 (₩50,000 이상 무료)',
    delivery_time_val: '2-5 영업일',
    return_policy_val: '수령 후 7일 이내',
    refund_policy_val: '미개봉 제품 전액 환불',
    currently_viewing: '명이 보고 있음',
    added_today: '오늘 장바구니에 추가',
    total_sold: '총 판매',
    wishlist_count: '위시리스트',
    write_review: '리뷰 작성',
    review_title_placeholder: '리뷰 제목을 입력하세요',
    review_body_placeholder: '이 상품에 대한 솔직한 리뷰를 작성해 주세요...',
    submit_review: '리뷰 등록',
    your_name: '이름',
    your_rating: '별점',
    related_products: '관련 상품',
    same_country: '같은 나라 상품',
    recently_viewed: '최근 본 상품',
    question_placeholder: '질문을 입력해 주세요...',
    ask_question: '질문하기',
    // Filters
    filter_country: '국가',
    filter_category: '카테고리',
    filter_price: '가격',
    sort_by: '정렬',
    sort_best: '베스트셀러',
    sort_new: '신상품순',
    sort_low: '낮은 가격순',
    sort_high: '높은 가격순',
    // Login
    login: '로그인',
    register: '회원가입',
    email: '이메일',
    password: '비밀번호',
    confirm_password: '비밀번호 확인',
    name: '이름',
    forgot_password: '비밀번호를 잊으셨나요?',
    login_desc: '계정에 로그인하여 주문 및 위시리스트를 관리하세요.',
    register_desc: '새 계정을 만들어 더 편리하게 쇼핑하세요.',
    // Newsletter
    newsletter_title: '특별 혜택을 먼저 받아보세요',
    newsletter_sub: '신상품 소식, 할인 쿠폰, 이벤트를 이메일로 받아보세요.',
    newsletter_btn: '구독하기',
    newsletter_placeholder: '이메일 주소를 입력하세요',
    // About
    about_title: '아시아 최고의\n식품을 전합니다',
    about_sub: '세이위는 7개국 최고의 식품을 엄선하여 여러분의 식탁을 풍요롭게 합니다.',
    // Contact
    contact_title: '문의하기',
    contact_sub: '궁금한 점이 있으시면 언제든지 연락해 주세요.',
    send_message: '메시지 보내기',
    // Marquee
    marquee_items: ['무료배송 $50 이상', '100% 정품 보장', '신선도 보장', '7개국 직수입', '안전한 결제', '빠른 배송'],
    // Toast
    toast_added_cart: '장바구니에 추가되었습니다!',
    toast_added_wish: '위시리스트에 추가되었습니다!',
    toast_removed_wish: '위시리스트에서 제거되었습니다.',
    toast_removed_cart: '장바구니에서 제거되었습니다.',
    toast_newsletter: '구독해 주셔서 감사합니다!',
    toast_review: '리뷰가 등록되었습니다!',
    toast_login: '로그인 되었습니다!',
    toast_logout: '로그아웃 되었습니다.',
    toast_register: '회원가입이 완료되었습니다!',
    toast_question: '질문이 등록되었습니다!',
    // Blog
    blog_title: '블로그',
    blog_sub: '아시아 음식 문화와 레시피 이야기',
    // Wishlist
    wishlist_title: '위시리스트',
    wishlist_empty: '위시리스트가 비어 있습니다',
    wishlist_empty_sub: '좋아하는 상품을 위시리스트에 추가해 보세요',
    // Footer
    footer_about: '세이위는 7개국 최고의 아시아 식품을 한 곳에서 만날 수 있는 프리미엄 마켓플레이스입니다.',
    footer_shop: '쇼핑',
    footer_company: '회사',
    footer_support: '고객지원',
    footer_copyright: '© 2025 SAYWEE. All rights reserved.',
    // No results
    no_products: '상품을 찾을 수 없습니다.',
    // Ingredients
    ingredients: '원재료',
    allergens: '알레르기 정보',
    storage: '보관 방법',
    weight: '중량',
    expiry: '유통기한',
    brand: '브랜드',
    origin: '원산지',
    category: '카테고리',
  },

  en: {
    nav_home: 'HOME',
    nav_shop: 'SHOP',
    nav_countries: 'COUNTRIES',
    nav_event: 'EVENT',
    nav_blog: 'BLOG',
    nav_reviews: 'REVIEWS',
    nav_about: 'ABOUT',
    nav_contact: 'CONTACT',
    search_placeholder: 'Search products...',
    hero1_tag: 'New Arrivals',
    hero1_title: 'Asian Flavors,\nAll in One Place',
    hero1_desc: 'Discover the finest foods and groceries from 7 Asian countries.',
    hero1_btn: 'Shop Now',
    hero2_tag: 'Best Seller',
    hero2_title: 'Korean Ramen\nDone Right',
    hero2_desc: 'Explore popular Korean instant noodles like Shin Ramyun and Buldak.',
    hero2_btn: 'View Ramen',
    hero3_tag: 'Special Deal',
    hero3_title: 'Bubble Tea\nAt Home',
    hero3_desc: 'Make authentic Taiwanese bubble tea with our premium kit.',
    hero3_btn: 'Order Now',
    section_country: 'Shop by Country',
    section_country_sub: 'Choose the taste of your favorite country',
    section_bestseller: 'Best Sellers',
    section_bestseller_sub: 'Our most popular products',
    section_new: 'New Arrivals',
    section_new_sub: 'Fresh new products just arrived',
    section_drinks: 'Asian Drinks',
    section_drinks_sub: 'Popular beverage collection from across Asia',
    section_snacks: 'Asian Snacks',
    section_snacks_sub: 'Delicious snack collection from Asia',
    section_reviews: 'Customer Reviews',
    section_reviews_sub: 'Honest reviews from real customers',
    section_story: 'Our Story',
    section_insta: 'Follow us on Instagram',
    view_all: 'View All',
    add_to_cart: 'Add to Cart',
    add_to_wishlist: 'Wishlist',
    quick_view: 'Quick View',
    reviews_count: ' reviews',
    sold_count: 'sold',
    country_korea: 'Korea',
    country_japan: 'Japan',
    country_china: 'China',
    country_vietnam: 'Vietnam',
    country_thailand: 'Thailand',
    country_india: 'India',
    country_taiwan: 'Taiwan',
    cart_title: 'Shopping Cart',
    cart_empty: 'Your cart is empty',
    cart_empty_sub: 'Start shopping and add items you love',
    go_shopping: 'Go Shopping',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free_shipping: 'Free',
    total: 'Total',
    checkout: 'Checkout',
    coupon_placeholder: 'Enter coupon code',
    apply: 'Apply',
    remove: 'Remove',
    tab_description: 'Description',
    tab_nutrition: 'Nutrition',
    tab_reviews: 'Reviews',
    tab_qa: 'Q&A',
    add_cart: 'Add to Cart',
    buy_now: 'Buy Now',
    add_wish: 'Add to Wishlist',
    delivery_title: 'Delivery Info',
    shipping_fee: 'Shipping Fee',
    delivery_time: 'Delivery Time',
    return_policy: 'Return Policy',
    refund_policy: 'Refund Policy',
    shipping_fee_val: 'Free over $35',
    delivery_time_val: '3-7 business days',
    return_policy_val: 'Within 7 days of receipt',
    refund_policy_val: 'Full refund on unopened items',
    currently_viewing: 'currently viewing',
    added_today: 'added to cart today',
    total_sold: 'total sold',
    wishlist_count: 'wishlisted',
    write_review: 'Write a Review',
    review_title_placeholder: 'Enter a review title',
    review_body_placeholder: 'Share your honest thoughts about this product...',
    submit_review: 'Submit Review',
    your_name: 'Your Name',
    your_rating: 'Your Rating',
    related_products: 'Related Products',
    same_country: 'From the Same Country',
    recently_viewed: 'Recently Viewed',
    question_placeholder: 'Enter your question...',
    ask_question: 'Ask a Question',
    filter_country: 'Country',
    filter_category: 'Category',
    filter_price: 'Price',
    sort_by: 'Sort By',
    sort_best: 'Best Seller',
    sort_new: 'Newest',
    sort_low: 'Price: Low to High',
    sort_high: 'Price: High to Low',
    login: 'Log In',
    register: 'Sign Up',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    name: 'Full Name',
    forgot_password: 'Forgot password?',
    login_desc: 'Log in to manage your orders and wishlist.',
    register_desc: 'Create an account for a better shopping experience.',
    newsletter_title: 'Get Exclusive Deals First',
    newsletter_sub: 'Receive new arrivals, discount coupons, and events by email.',
    newsletter_btn: 'Subscribe',
    newsletter_placeholder: 'Enter your email address',
    about_title: 'Bringing the Best\nAsian Foods to You',
    about_sub: 'SAYWEE carefully curates the finest foods from 7 countries to enrich your table.',
    contact_title: 'Contact Us',
    contact_sub: 'Feel free to reach out anytime. We\'re here to help.',
    send_message: 'Send Message',
    marquee_items: ['Free Shipping over $35', '100% Authentic', 'Freshness Guaranteed', 'Direct Import from 7 Countries', 'Secure Payment', 'Fast Delivery'],
    toast_added_cart: 'Added to cart!',
    toast_added_wish: 'Added to wishlist!',
    toast_removed_wish: 'Removed from wishlist.',
    toast_removed_cart: 'Removed from cart.',
    toast_newsletter: 'Thanks for subscribing!',
    toast_review: 'Review submitted!',
    toast_login: 'Logged in successfully!',
    toast_logout: 'Logged out.',
    toast_register: 'Account created!',
    toast_question: 'Question submitted!',
    blog_title: 'Blog',
    blog_sub: 'Asian food culture and recipe stories',
    wishlist_title: 'Wishlist',
    wishlist_empty: 'Your wishlist is empty',
    wishlist_empty_sub: 'Add your favorite products to your wishlist',
    footer_about: 'SAYWEE is a premium marketplace bringing the finest Asian foods from 7 countries to one place.',
    footer_shop: 'Shop',
    footer_company: 'Company',
    footer_support: 'Support',
    footer_copyright: '© 2025 SAYWEE. All rights reserved.',
    no_products: 'No products found.',
    ingredients: 'Ingredients',
    allergens: 'Allergens',
    storage: 'Storage',
    weight: 'Weight',
    expiry: 'Best Before',
    brand: 'Brand',
    origin: 'Country of Origin',
    category: 'Category',
  },

  vi: {
    nav_home: 'TRANG CHỦ',
    nav_shop: 'CỬA HÀNG',
    nav_countries: 'QUỐC GIA',
    nav_event: 'SỰ KIỆN',
    nav_blog: 'BLOG',
    nav_reviews: 'ĐÁNH GIÁ',
    nav_about: 'GIỚI THIỆU',
    nav_contact: 'LIÊN HỆ',
    search_placeholder: 'Tìm kiếm sản phẩm...',
    hero1_tag: 'Hàng Mới Về',
    hero1_title: 'Hương Vị Châu Á\nTại Một Nơi',
    hero1_desc: 'Khám phá thực phẩm và đặc sản từ 7 quốc gia châu Á.',
    hero1_btn: 'Mua Ngay',
    hero2_tag: 'Bán Chạy Nhất',
    hero2_title: 'Mì Ramen Hàn Quốc\nĐích Thực',
    hero2_desc: 'Khám phá mì ăn liền Hàn Quốc nổi tiếng như Shin Ramyun và Buldak.',
    hero2_btn: 'Xem Mì',
    hero3_tag: 'Ưu Đãi Đặc Biệt',
    hero3_title: 'Trà Sữa Trân Châu\nTại Nhà',
    hero3_desc: 'Thưởng thức trà sữa Đài Loan chính hiệu với bộ kit cao cấp của chúng tôi.',
    hero3_btn: 'Đặt Hàng',
    section_country: 'Mua Theo Quốc Gia',
    section_country_sub: 'Chọn hương vị yêu thích của bạn',
    section_bestseller: 'Bán Chạy Nhất',
    section_bestseller_sub: 'Sản phẩm được yêu thích nhất',
    section_new: 'Hàng Mới Về',
    section_new_sub: 'Sản phẩm mới vừa nhập kho',
    section_drinks: 'Đồ Uống Châu Á',
    section_drinks_sub: 'Bộ sưu tập đồ uống từ khắp châu Á',
    section_snacks: 'Đồ Ăn Vặt Châu Á',
    section_snacks_sub: 'Bộ sưu tập bánh kẹo từ châu Á',
    section_reviews: 'Đánh Giá Khách Hàng',
    section_reviews_sub: 'Nhận xét chân thật từ khách hàng thực tế',
    section_story: 'Câu Chuyện Của Chúng Tôi',
    section_insta: 'Theo dõi chúng tôi trên Instagram',
    view_all: 'Xem Tất Cả',
    add_to_cart: 'Thêm Vào Giỏ',
    add_to_wishlist: 'Yêu Thích',
    quick_view: 'Xem Nhanh',
    reviews_count: ' đánh giá',
    sold_count: 'đã bán',
    country_korea: 'Hàn Quốc',
    country_japan: 'Nhật Bản',
    country_china: 'Trung Quốc',
    country_vietnam: 'Việt Nam',
    country_thailand: 'Thái Lan',
    country_india: 'Ấn Độ',
    country_taiwan: 'Đài Loan',
    cart_title: 'Giỏ Hàng',
    cart_empty: 'Giỏ hàng của bạn đang trống',
    cart_empty_sub: 'Hãy bắt đầu mua sắm và thêm những sản phẩm bạn yêu thích',
    go_shopping: 'Đi Mua Sắm',
    subtotal: 'Tạm tính',
    shipping: 'Vận chuyển',
    free_shipping: 'Miễn phí',
    total: 'Tổng cộng',
    checkout: 'Thanh Toán',
    coupon_placeholder: 'Nhập mã giảm giá',
    apply: 'Áp dụng',
    remove: 'Xóa',
    tab_description: 'Mô Tả',
    tab_nutrition: 'Dinh Dưỡng',
    tab_reviews: 'Đánh Giá',
    tab_qa: 'Hỏi Đáp',
    add_cart: 'Thêm Vào Giỏ',
    buy_now: 'Mua Ngay',
    add_wish: 'Thêm Vào Yêu Thích',
    delivery_title: 'Thông Tin Giao Hàng',
    shipping_fee: 'Phí vận chuyển',
    delivery_time: 'Thời gian giao hàng',
    return_policy: 'Chính sách đổi trả',
    refund_policy: 'Chính sách hoàn tiền',
    shipping_fee_val: 'Miễn phí đơn trên 500k',
    delivery_time_val: '3-7 ngày làm việc',
    return_policy_val: 'Trong vòng 7 ngày nhận hàng',
    refund_policy_val: 'Hoàn tiền 100% sản phẩm chưa mở',
    currently_viewing: 'người đang xem',
    added_today: 'đã thêm vào giỏ hôm nay',
    total_sold: 'đã bán',
    wishlist_count: 'yêu thích',
    write_review: 'Viết Đánh Giá',
    review_title_placeholder: 'Nhập tiêu đề đánh giá',
    review_body_placeholder: 'Chia sẻ nhận xét chân thật của bạn về sản phẩm này...',
    submit_review: 'Gửi Đánh Giá',
    your_name: 'Họ tên',
    your_rating: 'Đánh giá',
    related_products: 'Sản Phẩm Liên Quan',
    same_country: 'Sản Phẩm Cùng Quốc Gia',
    recently_viewed: 'Đã Xem Gần Đây',
    question_placeholder: 'Nhập câu hỏi của bạn...',
    ask_question: 'Đặt Câu Hỏi',
    filter_country: 'Quốc gia',
    filter_category: 'Danh mục',
    filter_price: 'Giá',
    sort_by: 'Sắp xếp',
    sort_best: 'Bán chạy nhất',
    sort_new: 'Mới nhất',
    sort_low: 'Giá: Thấp đến cao',
    sort_high: 'Giá: Cao đến thấp',
    login: 'Đăng Nhập',
    register: 'Đăng Ký',
    email: 'Email',
    password: 'Mật khẩu',
    confirm_password: 'Xác nhận mật khẩu',
    name: 'Họ và tên',
    forgot_password: 'Quên mật khẩu?',
    login_desc: 'Đăng nhập để quản lý đơn hàng và danh sách yêu thích.',
    register_desc: 'Tạo tài khoản để mua sắm tiện lợi hơn.',
    newsletter_title: 'Nhận Ưu Đãi Độc Quyền Đầu Tiên',
    newsletter_sub: 'Nhận thông tin hàng mới, mã giảm giá và sự kiện qua email.',
    newsletter_btn: 'Đăng Ký',
    newsletter_placeholder: 'Nhập địa chỉ email của bạn',
    about_title: 'Mang Hương Vị Châu Á\nĐến Với Bạn',
    about_sub: 'SAYWEE chọn lọc kỹ càng những thực phẩm tốt nhất từ 7 quốc gia để làm phong phú thêm bàn ăn của bạn.',
    contact_title: 'Liên Hệ',
    contact_sub: 'Hãy liên hệ bất cứ lúc nào. Chúng tôi luôn sẵn sàng hỗ trợ.',
    send_message: 'Gửi Tin Nhắn',
    marquee_items: ['Miễn phí ship đơn trên 500k', 'Hàng chính hãng 100%', 'Đảm bảo độ tươi', 'Nhập khẩu trực tiếp từ 7 quốc gia', 'Thanh toán an toàn', 'Giao hàng nhanh chóng'],
    toast_added_cart: 'Đã thêm vào giỏ hàng!',
    toast_added_wish: 'Đã thêm vào yêu thích!',
    toast_removed_wish: 'Đã xóa khỏi yêu thích.',
    toast_removed_cart: 'Đã xóa khỏi giỏ hàng.',
    toast_newsletter: 'Cảm ơn bạn đã đăng ký!',
    toast_review: 'Đánh giá đã được gửi!',
    toast_login: 'Đăng nhập thành công!',
    toast_logout: 'Đã đăng xuất.',
    toast_register: 'Đăng ký thành công!',
    toast_question: 'Câu hỏi đã được gửi!',
    blog_title: 'Blog',
    blog_sub: 'Văn hóa ẩm thực châu Á và các câu chuyện công thức nấu ăn',
    wishlist_title: 'Yêu Thích',
    wishlist_empty: 'Danh sách yêu thích của bạn đang trống',
    wishlist_empty_sub: 'Hãy thêm những sản phẩm bạn yêu thích vào đây',
    footer_about: 'SAYWEE là sàn thương mại điện tử cao cấp mang đến những thực phẩm châu Á tốt nhất từ 7 quốc gia.',
    footer_shop: 'Mua Sắm',
    footer_company: 'Công Ty',
    footer_support: 'Hỗ Trợ',
    footer_copyright: '© 2025 SAYWEE. Bảo lưu mọi quyền.',
    no_products: 'Không tìm thấy sản phẩm.',
    ingredients: 'Thành phần',
    allergens: 'Chất gây dị ứng',
    storage: 'Bảo quản',
    weight: 'Trọng lượng',
    expiry: 'Hạn sử dụng',
    brand: 'Thương hiệu',
    origin: 'Xuất xứ',
    category: 'Danh mục',
  },

  ja: {
    nav_home: 'ホーム',
    nav_shop: 'ショップ',
    nav_countries: '国別',
    nav_event: 'イベント',
    nav_blog: 'ブログ',
    nav_reviews: 'レビュー',
    nav_about: '紹介',
    nav_contact: 'お問合せ',
    search_placeholder: '商品を検索...',
    hero1_tag: '新着商品',
    hero1_title: 'アジアの味を\nひとつの場所で',
    hero1_desc: '7か国のベスト食品・食材を直接お届けします。',
    hero1_btn: '今すぐ買う',
    hero2_tag: 'ベストセラー',
    hero2_title: '韓国ラーメンの\n定番',
    hero2_desc: '辛ラーメン、ブルダック炒め麺など人気韓国ラーメン。',
    hero2_btn: 'ラーメンを見る',
    hero3_tag: '特別割引',
    hero3_title: 'タピオカティーを\n自宅で',
    hero3_desc: '台湾本格バブルティーキットでカフェの味を楽しもう。',
    hero3_btn: '今すぐ注文',
    section_country: '国別ショッピング',
    section_country_sub: 'お好きな国の味を選んでください',
    section_bestseller: 'ベストセラー',
    section_bestseller_sub: '最も人気の商品',
    section_new: '新着商品',
    section_new_sub: '新しく入荷した商品',
    section_drinks: 'アジアドリンク',
    section_drinks_sub: '各国の人気ドリンクコレクション',
    section_snacks: 'アジアスナック',
    section_snacks_sub: 'おいしいアジアのおやつ',
    section_reviews: 'お客様レビュー',
    section_reviews_sub: '実際の購入者の口コミ',
    section_story: 'SAYWEEのストーリー',
    section_insta: 'Instagramをフォロー',
    view_all: 'すべて見る',
    add_to_cart: 'カートに追加',
    add_to_wishlist: 'ウィッシュリスト',
    quick_view: 'クイックビュー',
    reviews_count: ' レビュー',
    sold_count: '販売済み',
    country_korea: '韓国',
    country_japan: '日本',
    country_china: '中国',
    country_vietnam: 'ベトナム',
    country_thailand: 'タイ',
    country_india: 'インド',
    country_taiwan: '台湾',
    cart_title: 'ショッピングカート',
    cart_empty: 'カートは空です',
    cart_empty_sub: 'お気に入りの商品をカートに追加してください',
    go_shopping: 'ショッピングへ',
    subtotal: '小計',
    shipping: '送料',
    free_shipping: '無料',
    total: '合計',
    checkout: 'お会計',
    coupon_placeholder: 'クーポンコードを入力',
    apply: '適用',
    remove: '削除',
    tab_description: '商品説明',
    tab_nutrition: '栄養情報',
    tab_reviews: 'レビュー',
    tab_qa: 'Q&A',
    add_cart: 'カートに追加',
    buy_now: '今すぐ購入',
    add_wish: 'ウィッシュリストに追加',
    delivery_title: '配送情報',
    shipping_fee: '送料',
    delivery_time: '配送期間',
    return_policy: '返品ポリシー',
    refund_policy: '返金ポリシー',
    shipping_fee_val: '$35以上送料無料',
    delivery_time_val: '3〜7営業日',
    return_policy_val: '受取後7日以内',
    refund_policy_val: '未開封商品全額返金',
    currently_viewing: '人が閲覧中',
    added_today: '本日カートに追加',
    total_sold: '総販売数',
    wishlist_count: 'ウィッシュリスト',
    write_review: 'レビューを書く',
    review_title_placeholder: 'レビュータイトル',
    review_body_placeholder: 'この商品についての率直な感想を書いてください...',
    submit_review: 'レビューを投稿',
    your_name: 'お名前',
    your_rating: '評価',
    related_products: '関連商品',
    same_country: '同じ国の商品',
    recently_viewed: '最近見た商品',
    question_placeholder: 'ご質問を入力...',
    ask_question: '質問する',
    filter_country: '国',
    filter_category: 'カテゴリー',
    filter_price: '価格',
    sort_by: '並び替え',
    sort_best: 'ベストセラー',
    sort_new: '新着順',
    sort_low: '価格が低い順',
    sort_high: '価格が高い順',
    login: 'ログイン',
    register: '会員登録',
    email: 'メールアドレス',
    password: 'パスワード',
    confirm_password: 'パスワード確認',
    name: 'お名前',
    forgot_password: 'パスワードをお忘れですか？',
    login_desc: 'ログインして注文とウィッシュリストを管理しましょう。',
    register_desc: 'アカウントを作成してより便利にショッピングしましょう。',
    newsletter_title: '特別特典を先に受け取る',
    newsletter_sub: '新着情報、割引クーポン、イベントをメールで受け取る。',
    newsletter_btn: '登録する',
    newsletter_placeholder: 'メールアドレスを入力',
    about_title: 'アジア最高の\n食品をお届けします',
    about_sub: 'SAYWEEは7か国の最高の食品を厳選してお届けします。',
    contact_title: 'お問合せ',
    contact_sub: 'ご不明な点はいつでもお気軽にご連絡ください。',
    send_message: 'メッセージを送る',
    marquee_items: ['$35以上送料無料', '100%正規品保証', '鮮度保証', '7カ国直輸入', '安全なお支払い', '迅速配送'],
    toast_added_cart: 'カートに追加しました！',
    toast_added_wish: 'ウィッシュリストに追加しました！',
    toast_removed_wish: 'ウィッシュリストから削除しました。',
    toast_removed_cart: 'カートから削除しました。',
    toast_newsletter: 'ご登録ありがとうございます！',
    toast_review: 'レビューを投稿しました！',
    toast_login: 'ログインしました！',
    toast_logout: 'ログアウトしました。',
    toast_register: '会員登録が完了しました！',
    toast_question: '質問を投稿しました！',
    blog_title: 'ブログ',
    blog_sub: 'アジア料理文化とレシピの話',
    wishlist_title: 'ウィッシュリスト',
    wishlist_empty: 'ウィッシュリストは空です',
    wishlist_empty_sub: 'お気に入りの商品を追加してください',
    footer_about: 'SAYWEEは7か国のアジアベスト食品が集まるプレミアムマーケットプレイスです。',
    footer_shop: 'ショップ',
    footer_company: '会社',
    footer_support: 'サポート',
    footer_copyright: '© 2025 SAYWEE. All rights reserved.',
    no_products: '商品が見つかりません。',
    ingredients: '原材料',
    allergens: 'アレルギー情報',
    storage: '保存方法',
    weight: '重量',
    expiry: '賞味期限',
    brand: 'ブランド',
    origin: '原産国',
    category: 'カテゴリー',
  },

  zh: {
    nav_home: '首页',
    nav_shop: '购物',
    nav_countries: '按国家',
    nav_event: '活动',
    nav_blog: '博客',
    nav_reviews: '评价',
    nav_about: '关于',
    nav_contact: '联系',
    search_placeholder: '搜索商品...',
    hero1_tag: '新品上架',
    hero1_title: '亚洲美味\n尽在一处',
    hero1_desc: '直接体验7个国家的顶级食品和食材。',
    hero1_btn: '立即购物',
    hero2_tag: '畅销商品',
    hero2_title: '韩国拉面\n正宗之选',
    hero2_desc: '辛拉面、三养炒鸡面等热门韩国泡面。',
    hero2_btn: '查看拉面',
    hero3_tag: '特别优惠',
    hero3_title: '在家享用\n珍珠奶茶',
    hero3_desc: '用台湾正宗珍珠奶茶套装，在家享受咖啡馆的味道。',
    hero3_btn: '立即订购',
    section_country: '按国家购物',
    section_country_sub: '选择您喜欢的国家美食',
    section_bestseller: '畅销商品',
    section_bestseller_sub: '最受欢迎的商品',
    section_new: '新品上架',
    section_new_sub: '最新入库商品',
    section_drinks: '亚洲饮品',
    section_drinks_sub: '各国人气饮品合集',
    section_snacks: '亚洲零食',
    section_snacks_sub: '美味亚洲零食精选',
    section_reviews: '顾客评价',
    section_reviews_sub: '真实购买者的诚实评价',
    section_story: 'SAYWEE的故事',
    section_insta: '关注我们的Instagram',
    view_all: '查看全部',
    add_to_cart: '加入购物车',
    add_to_wishlist: '收藏',
    quick_view: '快速查看',
    reviews_count: ' 条评价',
    sold_count: '已售',
    country_korea: '韩国',
    country_japan: '日本',
    country_china: '中国',
    country_vietnam: '越南',
    country_thailand: '泰国',
    country_india: '印度',
    country_taiwan: '台湾',
    cart_title: '购物车',
    cart_empty: '购物车是空的',
    cart_empty_sub: '开始购物，将喜欢的商品加入购物车',
    go_shopping: '去购物',
    subtotal: '小计',
    shipping: '运费',
    free_shipping: '免费',
    total: '合计',
    checkout: '结账',
    coupon_placeholder: '输入优惠码',
    apply: '应用',
    remove: '删除',
    tab_description: '商品描述',
    tab_nutrition: '营养信息',
    tab_reviews: '评价',
    tab_qa: '问答',
    add_cart: '加入购物车',
    buy_now: '立即购买',
    add_wish: '加入收藏',
    delivery_title: '配送信息',
    shipping_fee: '运费',
    delivery_time: '配送时间',
    return_policy: '退货政策',
    refund_policy: '退款政策',
    shipping_fee_val: '$35以上免运费',
    delivery_time_val: '3-7个工作日',
    return_policy_val: '收货后7天内',
    refund_policy_val: '未开封商品全额退款',
    currently_viewing: '人正在浏览',
    added_today: '今日加入购物车',
    total_sold: '总销量',
    wishlist_count: '收藏',
    write_review: '写评价',
    review_title_placeholder: '输入评价标题',
    review_body_placeholder: '请写下您对此商品的真实感受...',
    submit_review: '提交评价',
    your_name: '您的姓名',
    your_rating: '您的评分',
    related_products: '相关商品',
    same_country: '同一国家商品',
    recently_viewed: '最近浏览',
    question_placeholder: '输入您的问题...',
    ask_question: '提问',
    filter_country: '国家',
    filter_category: '分类',
    filter_price: '价格',
    sort_by: '排序',
    sort_best: '畅销',
    sort_new: '最新',
    sort_low: '价格从低到高',
    sort_high: '价格从高到低',
    login: '登录',
    register: '注册',
    email: '邮箱',
    password: '密码',
    confirm_password: '确认密码',
    name: '姓名',
    forgot_password: '忘记密码？',
    login_desc: '登录以管理您的订单和收藏。',
    register_desc: '创建账户，享受更便捷的购物体验。',
    newsletter_title: '率先获取专属优惠',
    newsletter_sub: '通过邮件接收新品信息、折扣券和活动通知。',
    newsletter_btn: '订阅',
    newsletter_placeholder: '输入您的邮箱地址',
    about_title: '为您带来\n亚洲顶级美食',
    about_sub: 'SAYWEE精心挑选7个国家的顶级食品，丰富您的餐桌。',
    contact_title: '联系我们',
    contact_sub: '如有疑问，随时联系我们。',
    send_message: '发送消息',
    marquee_items: ['$35以上免运费', '100%正品保证', '新鲜度保证', '7国直接进口', '安全支付', '快速配送'],
    toast_added_cart: '已加入购物车！',
    toast_added_wish: '已加入收藏！',
    toast_removed_wish: '已从收藏中删除。',
    toast_removed_cart: '已从购物车删除。',
    toast_newsletter: '感谢您的订阅！',
    toast_review: '评价已提交！',
    toast_login: '登录成功！',
    toast_logout: '已退出登录。',
    toast_register: '注册成功！',
    toast_question: '问题已提交！',
    blog_title: '博客',
    blog_sub: '亚洲饮食文化与食谱故事',
    wishlist_title: '我的收藏',
    wishlist_empty: '收藏列表为空',
    wishlist_empty_sub: '将喜欢的商品加入收藏',
    footer_about: 'SAYWEE是汇集7个国家顶级亚洲食品的高端市场平台。',
    footer_shop: '购物',
    footer_company: '公司',
    footer_support: '客户支持',
    footer_copyright: '© 2025 SAYWEE. 保留所有权利。',
    no_products: '未找到商品。',
    ingredients: '成分',
    allergens: '过敏原信息',
    storage: '储存方式',
    weight: '重量',
    expiry: '保质期',
    brand: '品牌',
    origin: '产地',
    category: '分类',
  },

};

// Language Manager
const LangManager = {
  current: localStorage.getItem('saywee_lang') || 'ko',

  get(key) {
    const t = TRANSLATIONS[this.current];
    return (t && t[key]) || TRANSLATIONS['en'][key] || key;
  },

  set(lang) {
    if (!TRANSLATIONS[lang]) return;
    this.current = lang;
    localStorage.setItem('saywee_lang', lang);
    this.apply();
  },

  apply() {
    // Update all elements with data-lang attribute
    document.querySelectorAll('[data-lang]').forEach(el => {
      const key = el.getAttribute('data-lang');
      const val = this.get(key);
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
        el.placeholder = val;
      } else {
        el.textContent = val;
      }
    });

    // Update placeholders
    document.querySelectorAll('[data-lang-placeholder]').forEach(el => {
      el.placeholder = this.get(el.getAttribute('data-lang-placeholder'));
    });

    // Update language switcher active state
    document.querySelectorAll('.lang-option').forEach(opt => {
      opt.classList.toggle('active', opt.dataset.lang === this.current);
    });

    // Update flag button
    const langFlags = { ko: '🇰🇷 KR', en: '🇺🇸 EN', vi: '🇻🇳 VI', ja: '🇯🇵 JP', zh: '🇨🇳 ZH' };
    const btn = document.querySelector('.lang-btn');
    if (btn) btn.textContent = langFlags[this.current] || 'KR';

    // Fire event for pages that need to re-render
    document.dispatchEvent(new Event('langChange'));
  },

  init() {
    this.apply();
    document.querySelectorAll('.lang-option').forEach(opt => {
      opt.addEventListener('click', () => this.set(opt.dataset.lang));
    });
  }
};
